
development:
  adapter: postgresql
  encoding: utf8
  database: testpj_development
  pool: 5
  

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: testpj_test
  pool: 5
  

production:
  adapter: postgresql
  encoding: utf8
  database: testpj_production
  pool: 5
  

cucumber:
  <<: *TEST